AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crud-app

  Sample SAM Template for crud-app


Globals:
  Function:
    Timeout: 30

Parameters:
  # Region:
  #   Type: String
  #   Default: us-east-2
  # AWSEnv:
  #   Type: String
  #   Default: AWS  
  Table:
    Type: String
    Default: Activities


Resources:
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/Create-function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:  
        Variables:
          TABLE: !Ref Table
          # REGION: !Ref Region
          # AWSENV: !Ref AWSEnv
      Events:
        CreateOperation:
          Type: Api
          Properties:
            Path:  /activities
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable

  ReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/Read-function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:  
        Variables:
          TABLE: !Ref Table
          # REGION: !Ref Region
          # AWSENV: !Ref AWSEnv
      Events:
        CreateOperation:
          Type: Api
          Properties:
            Path:  /activities/{id}
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable

  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/Update-function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:  
        Variables:
          TABLE: !Ref Table
          # REGION: !Ref Region
          # AWSENV: !Ref AWSEnv
      Events:
        CreateOperation:
          Type: Api
          Properties:
            Path:  /activities/{id}
            Method: put
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/Delete-function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:  
        Variables:
          TABLE: !Ref Table
          # REGION: !Ref Region
          # AWSENV: !Ref AWSEnv
      Events:
        CreateOperation:
          Type: Api
          Properties:
            Path:  /activities/{id}/{date}
            Method: delete
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable

  ActivitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
        -
          AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "date"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "Activities"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
